// Seed content so the app feels alive on first open.
export const SAMPLE_RECIPES = [
  {
    id: 'r-greek-bowl',
    title: 'Greek Quinoa Power Bowl',
    emoji: '🥗',
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    minutes: 25,
    servings: 2,
    calories: 420,
    macros: { protein: 22, carbs: 48, fat: 16 },
    tags: ['High Protein', 'Vegetarian', 'Meal Prep'],
    ingredients: [
      '1 cup cooked quinoa',
      '1 cup cherry tomatoes, halved',
      '1 cucumber, diced',
      '1/2 red onion, thinly sliced',
      '1/2 cup kalamata olives',
      '100g feta cheese, crumbled',
      '2 tbsp olive oil',
      '1 lemon, juiced',
      'Salt, pepper, dried oregano',
    ],
    steps: [
      'Cook quinoa per package and let cool slightly.',
      'Chop tomatoes, cucumber, and red onion.',
      'Whisk olive oil, lemon juice, oregano, salt and pepper.',
      'Combine everything in a bowl, top with feta and olives.',
      'Drizzle with dressing and serve.',
    ],
    source: 'Sample recipe',
  },
  {
    id: 'r-miso-ramen',
    title: 'Light Miso Ramen',
    emoji: '🍜',
    cuisine: 'Japanese',
    difficulty: 'Medium',
    minutes: 20,
    servings: 1,
    calories: 380,
    macros: { protein: 15, carbs: 52, fat: 11 },
    tags: ['Comfort', 'Quick'],
    ingredients: [
      '1 portion ramen noodles',
      '2 tbsp white miso paste',
      '500ml vegetable stock',
      '1 soft-boiled egg',
      '1 cup spinach',
      '2 spring onions, sliced',
      '1 tsp sesame oil',
    ],
    steps: [
      'Warm stock and whisk in miso paste (do not boil).',
      'Cook noodles separately until just tender.',
      'Wilt spinach in the broth for 1 minute.',
      'Assemble noodles, broth, halved egg and spring onions.',
      'Finish with a drizzle of sesame oil.',
    ],
    source: 'Sample recipe',
  },
  {
    id: 'r-egg-scramble',
    title: 'Veggie Egg Scramble',
    emoji: '🍳',
    cuisine: 'American',
    difficulty: 'Easy',
    minutes: 10,
    servings: 1,
    calories: 310,
    macros: { protein: 18, carbs: 9, fat: 22 },
    tags: ['Breakfast', 'Low Carb', 'Quick'],
    ingredients: [
      '3 eggs',
      '1/2 bell pepper, diced',
      '1/4 cup mushrooms, sliced',
      'Handful of spinach',
      '1 tbsp butter',
      'Salt and pepper',
    ],
    steps: [
      'Melt butter in a non-stick pan over medium heat.',
      'Sauté pepper and mushrooms for 3 minutes.',
      'Add spinach until wilted.',
      'Pour in beaten eggs and gently scramble.',
      'Season and serve immediately.',
    ],
    source: 'Sample recipe',
  },
]

export const SAMPLE_PANTRY = [
  'eggs', 'spinach', 'cherry tomatoes', 'olive oil', 'quinoa', 'feta cheese', 'onion', 'garlic',
]

export const STARTER_GOAL = {
  calories: 1840,
  protein: 120,
  carbs: 220,
  fat: 65,
}
